//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHGR.Models.Relational
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_phenotypes
    {
        public int id { get; set; }
        public int phenotype_id { get; set; }
        public Nullable<System.DateTime> resulted_on { get; set; }
        public string report { get; set; }
    
        public virtual phenotype phenotype { get; set; }
    }
}
