//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHGR.Models.Relational
{
    using System;
    using System.Collections.Generic;
    
    public partial class variant_information_types
    {
        public variant_information_types()
        {
            this.patient_variant_information = new HashSet<patient_variant_information>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public byte source { get; set; }
    
        public virtual ICollection<patient_variant_information> patient_variant_information { get; set; }
    }
}
