USE [master]
GO

alter database [mhgr_eav] set single_user with rollback immediate

IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'mhgr_eav')
DROP DATABASE [mhgr_eav]
GO


USE [master]
GO

/****** Object:  Database [mhgr_eav]    Script Date: 8/17/2015 9:54:42 PM ******/
CREATE DATABASE [mhgr_eav]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mhgr_eav', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.BASHERDB\MSSQL\DATA\mhgr_eav.mdf' , SIZE = 76800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'mhgr_eav_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.BASHERDB\MSSQL\DATA\mhgr_eav_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [mhgr_eav] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mhgr_eav].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mhgr_eav] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mhgr_eav] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mhgr_eav] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mhgr_eav] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mhgr_eav] SET ARITHABORT OFF 
GO

ALTER DATABASE [mhgr_eav] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mhgr_eav] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mhgr_eav] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mhgr_eav] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mhgr_eav] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mhgr_eav] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mhgr_eav] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mhgr_eav] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mhgr_eav] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mhgr_eav] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mhgr_eav] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mhgr_eav] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mhgr_eav] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mhgr_eav] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mhgr_eav] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mhgr_eav] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mhgr_eav] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mhgr_eav] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mhgr_eav] SET  MULTI_USER 
GO

ALTER DATABASE [mhgr_eav] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mhgr_eav] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mhgr_eav] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mhgr_eav] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [mhgr_eav] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [mhgr_eav] SET  READ_WRITE 
GO

