//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHGR.EAVModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class attribute_relationships
    {
        public int id { get; set; }
        public int attribute1_id { get; set; }
        public int attribute2_id { get; set; }
        public int relationship_id { get; set; }
    
        public virtual attribute attribute { get; set; }
        public virtual attribute attribute1 { get; set; }
        public virtual attribute attribute2 { get; set; }
    }
}
