//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAVModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EAVEntities : DbContext
    {
        public EAVEntities()
            : base("name=EAVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attribute> attributes { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<result_entities> result_entities { get; set; }
        public virtual DbSet<result_files> result_files { get; set; }
        public virtual DbSet<result_sources> result_sources { get; set; }
    }
}
