//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHGR.Models.Hybrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_variant_information
    {
        public int id { get; set; }
        public int item_id { get; set; }
        public byte item_type { get; set; }
        public int type_id { get; set; }
        public string value { get; set; }
    
        public virtual variant_information_types variant_information_types { get; set; }
    }
}
