//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHGR.Models.Hybrid
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public patient()
        {
            this.patient_result_collections = new HashSet<patient_result_collections>();
            this.patient_variants = new HashSet<patient_variants>();
        }
    
        public int id { get; set; }
        public string external_id { get; set; }
        public string external_source { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
    
        public virtual ICollection<patient_result_collections> patient_result_collections { get; set; }
        public virtual ICollection<patient_variants> patient_variants { get; set; }
    }
}
